/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerardo_martinez.mavenproject1;

import java.awt.Color;
import javax.swing.JPanel;
import java.awt.*;
import javax.swing.*;
import javax.swing.SwingUtilities;

/**
 *
 * @author Bachillerato
 */
public class int_grafi_while extends javax.swing.JFrame {

    /**
     * Creates new form int_while
     */
    public int_grafi_while() {
        initComponents();
    }

    public class PanelDegradado extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g;

            float[] fractions = {0f, 0.5f, 1f};
            Color[] colors = {
                new Color(71, 28, 58),
                new Color(12, 25, 42),
                new Color(5, 76, 118)
            };

            LinearGradientPaint lgp = new LinearGradientPaint(0, 0, 0, getHeight(), fractions, colors);
            g2.setPaint(lgp);
            g2.fillRect(0, 0, getWidth(), getHeight());
        }

        public static void main(String[] args) {
            SwingUtilities.invokeLater(() -> {
                JFrame frame = new JFrame("Degradado 3 colores");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setSize(400, 400);
                frame.setVisible(true);
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jPanel1 = new PanelDegradado();
        Lim_pant = new javax.swing.JButton();
        boton_imprimir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_texto1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area_texto2 = new javax.swing.JTextArea();
        B_imprimir = new javax.swing.JButton();
        Input_datos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        B_salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu18.setText("File");
        jMenuBar6.add(jMenu18);

        jMenu19.setText("Edit");
        jMenuBar6.add(jMenu19);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lim_pant.setBackground(new java.awt.Color(5, 76, 118));
        Lim_pant.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Lim_pant.setForeground(new java.awt.Color(211, 143, 191));
        Lim_pant.setText("limpiar pantalla");
        Lim_pant.setToolTipText("Limpiar pantalla para ambos campos");
        Lim_pant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Lim_pant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limp_pant(evt);
            }
        });

        boton_imprimir.setBackground(new java.awt.Color(5, 76, 118));
        boton_imprimir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        boton_imprimir.setForeground(new java.awt.Color(211, 143, 191));
        boton_imprimir.setText("imprimir texto");
        boton_imprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        boton_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_imprimir(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBar(null);

        area_texto1.setEditable(false);
        area_texto1.setBackground(new java.awt.Color(5, 76, 118));
        area_texto1.setColumns(20);
        area_texto1.setForeground(new java.awt.Color(211, 143, 191));
        area_texto1.setRows(5);
        area_texto1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        area_texto1.setFocusable(false);
        jScrollPane1.setViewportView(area_texto1);

        jScrollPane2.setHorizontalScrollBar(null);

        Area_texto2.setEditable(false);
        Area_texto2.setBackground(new java.awt.Color(5, 76, 118));
        Area_texto2.setColumns(20);
        Area_texto2.setForeground(new java.awt.Color(211, 143, 191));
        Area_texto2.setRows(5);
        Area_texto2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Area_texto2.setCaretColor(new java.awt.Color(60, 63, 65));
        Area_texto2.setDragEnabled(true);
        Area_texto2.setFocusable(false);
        jScrollPane2.setViewportView(Area_texto2);

        B_imprimir.setBackground(new java.awt.Color(5, 76, 118));
        B_imprimir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        B_imprimir.setForeground(new java.awt.Color(211, 143, 191));
        B_imprimir.setText("Imprimir  texto");
        B_imprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_imprimir2(evt);
            }
        });

        Input_datos.setBackground(new java.awt.Color(5, 76, 118));
        Input_datos.setForeground(new java.awt.Color(211, 143, 191));
        Input_datos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(211, 143, 191));
        jLabel1.setText("ingresa un numero:");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(211, 143, 191));
        jLabel2.setText("Bucles while");

        B_salir.setBackground(new java.awt.Color(5, 76, 118));
        B_salir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        B_salir.setForeground(new java.awt.Color(211, 143, 191));
        B_salir.setText("Salir");
        B_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_salir(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(211, 143, 191));
        jLabel3.setText("Mostrar texto");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(211, 143, 191));
        jLabel4.setText("Contar asta N");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(141, 141, 141))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Input_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(B_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(boton_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lim_pant, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(B_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel2)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Input_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_imprimir)
                    .addComponent(Lim_pant)
                    .addComponent(boton_imprimir)
                    .addComponent(B_salir))
                .addGap(26, 26, 26))
        );

        jMenu1.setText("Primer parcial");
        jMenu1.setToolTipText("Ejercicios de áreas, magnitudes, otros.");

        jMenu8.setText("Calcular áreas");

        jMenuItem3.setText("Área del circulo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Circulo(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuItem5.setText("Área del rectángulo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rectangulo(evt);
            }
        });
        jMenu8.add(jMenuItem5);

        jMenuItem4.setText("Área del trapecio");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trapecio(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        jMenuItem2.setText("Área del triángulo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Triangulo(evt);
            }
        });
        jMenu8.add(jMenuItem2);

        jMenu1.add(jMenu8);

        jMenu9.setText("Magnitudes físicas");

        jMenuItem8.setText("Densidad");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Densidad(evt);
            }
        });
        jMenu9.add(jMenuItem8);

        jMenuItem6.setText("Masa");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masa(evt);
            }
        });
        jMenu9.add(jMenuItem6);

        jMenuItem7.setText("Volumen");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volumen(evt);
            }
        });
        jMenu9.add(jMenuItem7);

        jMenu1.add(jMenu9);

        jMenu10.setText("Otros ejercicios");

        jMenuItem9.setText("Fórmula Cuadrática");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_cuad(evt);
            }
        });
        jMenu10.add(jMenuItem9);

        jMenu1.add(jMenu10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sengundo parcial");
        jMenu2.setToolTipText("Ejercicios condisonales: if, switch, repetitivas.");

        jMenu12.setText("Condisional if");

        jMenuItem10.setText("Calcular Edad");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc_edad(evt);
            }
        });
        jMenu12.add(jMenuItem10);

        jMenuItem12.setText("Productos");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productos(evt);
            }
        });
        jMenu12.add(jMenuItem12);

        jMenuItem14.setText("Promedio");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Promedio(evt);
            }
        });
        jMenu12.add(jMenuItem14);

        jMenuItem13.setText("Verificar números pares");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ver_pares(evt);
            }
        });
        jMenu12.add(jMenuItem13);

        jMenuItem11.setText("Viajes");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Viajes(evt);
            }
        });
        jMenu12.add(jMenuItem11);

        jMenu2.add(jMenu12);

        jMenu13.setText("Estructura / switch");

        jMenuItem15.setText("Calculadora");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculadora(evt);
            }
        });
        jMenu13.add(jMenuItem15);

        jMenuItem16.setText("Menú áreas");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_areas(evt);
            }
        });
        jMenu13.add(jMenuItem16);

        jMenu2.add(jMenu13);

        jMenu11.setText("Estructuras de control iterativas");

        jMenu4.setText("Bucle for");

        jMenuItem17.setText("Lista de Números");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaa_num(evt);
            }
        });
        jMenu4.add(jMenuItem17);

        jMenuItem18.setText("Numeración");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeracion(evt);
            }
        });
        jMenu4.add(jMenuItem18);

        jMenuItem20.setText("Tabla del siete");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tabla_siete(evt);
            }
        });
        jMenu4.add(jMenuItem20);

        jMenuItem19.setText("Tablas de multiplicar");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablas_multip(evt);
            }
        });
        jMenu4.add(jMenuItem19);

        jMenu11.add(jMenu4);

        jMenu5.setText("Bucle while");

        jMenuItem21.setText("Suma de números");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suma_num_while(evt);
            }
        });
        jMenu5.add(jMenuItem21);

        jMenuItem22.setText("Sucesión Fibonacci");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serie_fibonacci(evt);
            }
        });
        jMenu5.add(jMenuItem22);

        jMenu11.add(jMenu5);

        jMenu6.setText("Bucle do while");
        jMenu11.add(jMenu6);

        jMenu2.add(jMenu11);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Menú inicio");
        jMenu3.setToolTipText("Regresar a el menú principal.");

        jMenuItem1.setText("Menú inicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_inicio(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_imprimir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_imprimir
        int i = 1;
        while (i <= 5) {
            area_texto1.append("Oropeza es mi Dios\n");
            i++;
        }


    }//GEN-LAST:event_B_imprimir

    private void limp_pant(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limp_pant
        area_texto1.setText("");
        Area_texto2.setText("");
    }//GEN-LAST:event_limp_pant

    private void B_imprimir2(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_imprimir2
        int i = 1;
        int numero = Integer.parseInt(Input_datos.getText());
        Area_texto2.setText(""); // limpiar antes

        while (i <= numero) {
            Area_texto2.append("\n" + i);
            i++;
        }

    }//GEN-LAST:event_B_imprimir2

    private void B_salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_salir
        dispose();
    }//GEN-LAST:event_B_salir

    private void Circulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Circulo
        int_graf_circ ventana_1 = new int_graf_circ();
        ventana_1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Circulo

    private void Rectangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rectangulo
        Interfaz_grafica_Rec ventana_2 = new Interfaz_grafica_Rec();
        ventana_2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Rectangulo

    private void Trapecio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trapecio
        Int_graf_trap ventana_3 = new Int_graf_trap();
        ventana_3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Trapecio

    private void Triangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Triangulo
        Interfaz_grafica_Tri ventana_4 = new Interfaz_grafica_Tri();
        ventana_4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Triangulo

    private void Densidad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Densidad
        Int_graf_densidad ventana_5 = new Int_graf_densidad();
        ventana_5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Densidad

    private void Masa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masa
        Int_graf_Masa ventana_6 = new Int_graf_Masa();
        ventana_6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Masa

    private void Volumen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volumen
        int_graf_volumen ventana_7 = new int_graf_volumen();
        ventana_7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Volumen

    private void Form_cuad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_cuad
        int_graf_formula_cu ventana_8 = new int_graf_formula_cu();
        ventana_8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Form_cuad

    private void Calc_edad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc_edad
        Int_graf_calc_edad ventana_9 = new Int_graf_calc_edad();
        ventana_9.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Calc_edad

    private void Productos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productos
        int_graf_produc ventana_10 = new int_graf_produc();
        ventana_10.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Productos

    private void Promedio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Promedio
        calc_calif ventana_12 = new calc_calif();
        ventana_12.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Promedio

    private void ver_pares(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ver_pares
        Int_graf_numero_par ventana_13 = new Int_graf_numero_par();
        ventana_13.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ver_pares

    private void Viajes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Viajes
        Int_graf_viajes ventana_14 = new Int_graf_viajes();
        ventana_14.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Viajes

    private void Calculadora(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculadora
        Int_graf_calculadora ventana_15 = new Int_graf_calculadora();
        ventana_15.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Calculadora

    private void menu_areas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_areas
        mini_menu_areas ventana_15 = new mini_menu_areas();
        ventana_15.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_areas

    private void listaa_num(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaa_num
        int_graf_lista_num ventana_16 = new int_graf_lista_num();
        ventana_16.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_listaa_num

    private void numeracion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeracion
        int_graf_num_10_20 ventana_17 = new int_graf_num_10_20();
        ventana_17.setVisible(true);
        this.dispose();    }//GEN-LAST:event_numeracion

    private void Tabla_siete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tabla_siete
        Tabla_del_siete ventana_18 = new Tabla_del_siete();
        ventana_18.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Tabla_siete

    private void tablas_multip(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablas_multip
        int_graf_tablas ventana_19 = new int_graf_tablas();
        ventana_19.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tablas_multip

    private void suma_num_while(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suma_num_while
        Int_graf_suma_while ventana_20 = new Int_graf_suma_while();
        ventana_20.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_suma_num_while

    private void serie_fibonacci(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serie_fibonacci
        int_graf_fibonacci ventana_21 = new int_graf_fibonacci();
        ventana_21.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_serie_fibonacci

    private void Menu_inicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_inicio
        Menu_gui ventana_22 = new Menu_gui();
        ventana_22.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_inicio

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(int_grafi_while.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(int_grafi_while.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(int_grafi_while.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(int_grafi_while.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new int_grafi_while().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area_texto2;
    private javax.swing.JButton B_imprimir;
    private javax.swing.JButton B_salir;
    private javax.swing.JTextField Input_datos;
    private javax.swing.JButton Lim_pant;
    private javax.swing.JTextArea area_texto1;
    private javax.swing.JButton boton_imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
