/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerardo_martinez.mavenproject1;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Bachillerato
 */
public class Int_graf_suma_while extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Int_graf_suma_while.class.getName());

    /**
     * Creates new form Int_graf_suma_while
     */
    public Int_graf_suma_while() {
        initComponents();
    }

    public class PanelDegradado extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g;

            GradientPaint gp = new GradientPaint(
                    0, 0, new Color(255, 223, 172),
                    0, getHeight(), new Color(175, 54, 59)
            );

            g2.setPaint(gp);
            g2.fillRect(0, 0, getWidth(), getHeight());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jPanel1 = new PanelDegradado();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        input_while = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ouput = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        B_calcular = new javax.swing.JButton();
        B_limpiarpantalla = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        jMenuItem17.setText("jMenuItem17");

        jMenuItem18.setText("jMenuItem18");

        jMenuItem22.setText("jMenuItem22");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(175, 54, 59));
        jLabel1.setText("Suma de los numeros con while");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(175, 54, 59));
        jLabel3.setText("Ingresa un numero entero");

        input_while.setBackground(new java.awt.Color(255, 223, 172));
        input_while.setForeground(new java.awt.Color(175, 54, 59));
        input_while.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(175, 54, 59));
        jLabel4.setText("Resultado de la suma del 1 asta tu numero");

        ouput.setEditable(false);
        ouput.setBackground(new java.awt.Color(255, 223, 172));
        ouput.setForeground(new java.awt.Color(175, 54, 59));
        ouput.setToolTipText("tus numeros se sumaron asi:\n\n1+2+3+n = tu numero \n");
        ouput.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ouput.setFocusable(false);

        jButton1.setBackground(new java.awt.Color(255, 223, 172));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(175, 54, 59));
        jButton1.setText("Salir");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(this::Salir);

        B_calcular.setBackground(new java.awt.Color(255, 223, 172));
        B_calcular.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        B_calcular.setForeground(new java.awt.Color(175, 54, 59));
        B_calcular.setText("calcular");
        B_calcular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_calcular.addActionListener(this::B_calcular);

        B_limpiarpantalla.setBackground(new java.awt.Color(255, 223, 172));
        B_limpiarpantalla.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        B_limpiarpantalla.setForeground(new java.awt.Color(175, 54, 59));
        B_limpiarpantalla.setText("limpiar pantalla");
        B_limpiarpantalla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_limpiarpantalla.addActionListener(this::B_limp);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(B_calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(B_limpiarpantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(15, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ouput, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(input_while, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(137, 137, 137))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_while, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ouput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_limpiarpantalla)
                            .addComponent(B_calcular)
                            .addComponent(jButton1))
                        .addGap(35, 35, 35))))
        );

        jMenu1.setText("Primer parcial ");
        jMenu1.setToolTipText("Ejercicios de áreas, magnitudes, otros.");

        jMenu4.setText("Calcular áreas");

        jMenuItem3.setText("Área del circulo");
        jMenuItem3.addActionListener(this::circulo);
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Área del rectángulo");
        jMenuItem4.addActionListener(this::Rectangulo);
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Área del trapecio");
        jMenuItem5.addActionListener(this::trapecio);
        jMenu4.add(jMenuItem5);

        jMenuItem2.setText("Área del triángulo");
        jMenuItem2.addActionListener(this::triangulo);
        jMenu4.add(jMenuItem2);

        jMenu1.add(jMenu4);

        jMenu5.setText("Magnitides Físicas");

        jMenuItem7.setText("Densidad");
        jMenuItem7.addActionListener(this::densidad);
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Masa");
        jMenuItem8.addActionListener(this::Masa);
        jMenu5.add(jMenuItem8);

        jMenuItem6.setText("Volumen");
        jMenuItem6.addActionListener(this::Volumen);
        jMenu5.add(jMenuItem6);

        jMenu1.add(jMenu5);

        jMenu6.setText("Otros ejercicios");

        jMenuItem9.setText("Fórmula cuadrática");
        jMenuItem9.addActionListener(this::formu_cuadratica);
        jMenu6.add(jMenuItem9);

        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Segundo parcial");
        jMenu2.setToolTipText("Ejercicios condisonales: if, switch, repetitivas.");

        jMenu8.setText("Condisional if");

        jMenuItem12.setText("Calcular edad");
        jMenuItem12.addActionListener(this::calc_edad);
        jMenu8.add(jMenuItem12);

        jMenuItem13.setText("Producto");
        jMenuItem13.addActionListener(this::prductos);
        jMenu8.add(jMenuItem13);

        jMenuItem10.setText("Promedio");
        jMenuItem10.addActionListener(this::promedio);
        jMenu8.add(jMenuItem10);

        jMenuItem11.setText("Viajes");
        jMenuItem11.addActionListener(this::Viajes);
        jMenu8.add(jMenuItem11);

        jMenu2.add(jMenu8);

        jMenu9.setText("Estructura / switch");

        jMenuItem14.setText("Calculadora");
        jMenuItem14.addActionListener(this::calculadora);
        jMenu9.add(jMenuItem14);

        jMenuItem15.setText("Menú áreas");
        jMenuItem15.addActionListener(this::Menu_areas);
        jMenu9.add(jMenuItem15);

        jMenu2.add(jMenu9);

        jMenu7.setText("Estructuras de control iterativas");

        jMenu11.setText("Bucle for");

        jMenuItem19.setText("Lista de Números");
        jMenuItem19.addActionListener(this::Lista_numeros);
        jMenu11.add(jMenuItem19);

        jMenuItem21.setText("Numeración");
        jMenuItem21.addActionListener(this::Numeracio);
        jMenu11.add(jMenuItem21);

        jMenuItem20.setText("Tabla del siete");
        jMenuItem20.addActionListener(this::Tabla_siete);
        jMenu11.add(jMenuItem20);

        jMenuItem16.setText("Tablas de multiplicar");
        jMenuItem16.addActionListener(this::tablas_multiplicar);
        jMenu11.add(jMenuItem16);

        jMenu7.add(jMenu11);

        jMenu12.setText("Bucle while");

        jMenuItem24.setText("Contar hasta N / Mostrar texto");
        jMenuItem24.addActionListener(this::contar_morstrar_texto);
        jMenu12.add(jMenuItem24);

        jMenuItem23.setText("Sucesión Fibonacci");
        jMenuItem23.addActionListener(this::Sucesion_fibonacci);
        jMenu12.add(jMenuItem23);

        jMenu7.add(jMenu12);

        jMenu10.setText("Bucle do while");
        jMenu7.add(jMenu10);

        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Menú inicio");
        jMenu3.setToolTipText("Regresar al menú principal.");

        jMenuItem1.setText("Menú inicio");
        jMenuItem1.addActionListener(this::Menu_inicio);
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void B_limp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_limp
        input_while.setText("");
        ouput.setText("");
    }//GEN-LAST:event_B_limp

    private void B_calcular(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_calcular
        int i = 0;
        int suma = 0;
        int numero_usu = Integer.parseInt(input_while.getText());

        while (i <= numero_usu) {
            suma += i;
            i++;
        }

        ouput.setText("" + suma);
    }//GEN-LAST:event_B_calcular

    private void Salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir
        dispose();
    }//GEN-LAST:event_Salir

    private void circulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circulo
        int_graf_circ ventana_1 = new int_graf_circ();
        ventana_1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_circulo

    private void Rectangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rectangulo
        Interfaz_grafica_Rec ventana_2 = new Interfaz_grafica_Rec();
        ventana_2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Rectangulo

    private void trapecio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trapecio
        Int_graf_trap ventana_3 = new Int_graf_trap();
        ventana_3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trapecio

    private void triangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangulo
        Interfaz_grafica_Tri ventana_4 = new Interfaz_grafica_Tri();
        ventana_4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_triangulo

    private void densidad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_densidad
        Int_graf_densidad ventana_5 = new Int_graf_densidad();
        ventana_5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_densidad

    private void Masa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masa
        Int_graf_Masa ventana_6 = new Int_graf_Masa();
        ventana_6.setVisible(true);
        this.dispose();    }//GEN-LAST:event_Masa

    private void Volumen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volumen
        int_graf_volumen ventana_7 = new int_graf_volumen();
        ventana_7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Volumen

    private void formu_cuadratica(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formu_cuadratica
        int_graf_formula_cu ventana_8 = new int_graf_formula_cu();
        ventana_8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formu_cuadratica

    private void calc_edad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_edad
        Int_graf_calc_edad ventana_9 = new Int_graf_calc_edad();
        ventana_9.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calc_edad

    private void prductos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prductos
        int_graf_produc ventana_10 = new int_graf_produc();
        ventana_10.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_prductos

    private void promedio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promedio
        calc_calif ventana_11 = new calc_calif();
        ventana_11.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_promedio

    private void Viajes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Viajes
        Int_graf_viajes ventana_12 = new Int_graf_viajes();
        ventana_12.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Viajes

    private void calculadora(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculadora
        Int_graf_calculadora ventana_13 = new Int_graf_calculadora();
        ventana_13.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calculadora

    private void Menu_areas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_areas
        mini_menu_areas ventana_14 = new mini_menu_areas();
        ventana_14.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_areas

    private void Lista_numeros(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_numeros
        int_graf_lista_num ventana_15 = new int_graf_lista_num();
        ventana_15.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Lista_numeros

    private void Numeracio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numeracio
        int_graf_num_10_20 ventana_16 = new int_graf_num_10_20();
        ventana_16.setVisible(true);
        this.dispose();    }//GEN-LAST:event_Numeracio

    private void Tabla_siete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tabla_siete
        Tabla_del_siete ventana_17 = new Tabla_del_siete();
        ventana_17.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Tabla_siete

    private void tablas_multiplicar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablas_multiplicar
        int_graf_tablas ventana_18 = new int_graf_tablas();
        ventana_18.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tablas_multiplicar

    private void contar_morstrar_texto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contar_morstrar_texto
        int_grafi_while ventana_19 = new int_grafi_while();
        ventana_19.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_contar_morstrar_texto

    private void Sucesion_fibonacci(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sucesion_fibonacci
        int_graf_fibonacci ventana_20 = new int_graf_fibonacci();
        ventana_20.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Sucesion_fibonacci

    private void Menu_inicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_inicio
        Menu_gui ventana_21 = new Menu_gui();
        ventana_21.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_inicio

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Int_graf_suma_while().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_calcular;
    private javax.swing.JButton B_limpiarpantalla;
    private javax.swing.JTextField input_while;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ouput;
    // End of variables declaration//GEN-END:variables
}
