/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerardo_martinez.mavenproject1;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Gerry-Mel
 */
public class int_graf_fibonacci extends javax.swing.JFrame {

    /**
     * Creates new form int_graf_fibonacci
     */
    public int_graf_fibonacci() {
        initComponents();
    }

    public class PanelDegradado extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g;

            GradientPaint gp = new GradientPaint(
                    0, 0, new Color(105, 253, 255),
                    0, getHeight(), new Color(105, 255, 114)
            );

            g2.setPaint(gp);
            g2.fillRect(0, 0, getWidth(), getHeight());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jPanel1 = new PanelDegradado();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_texto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        Input_fibo = new javax.swing.JTextField();
        B_salir = new javax.swing.JButton();
        Generar_serie = new javax.swing.JButton();
        B_limp_pant = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu5.setText("jMenu5");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem19.setText("jMenuItem19");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Secuencia de Fibonacci ");

        jScrollPane1.setFocusable(false);
        jScrollPane1.setHorizontalScrollBar(null);

        area_texto.setBackground(new java.awt.Color(57, 248, 250));
        area_texto.setColumns(20);
        area_texto.setForeground(new java.awt.Color(0, 153, 0));
        area_texto.setRows(5);
        area_texto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        area_texto.setFocusable(false);
        area_texto.setSelectionColor(new java.awt.Color(60, 63, 65));
        jScrollPane1.setViewportView(area_texto);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Ingresa un número entero para  generar serie:");

        Input_fibo.setBackground(new java.awt.Color(57, 248, 250));
        Input_fibo.setForeground(new java.awt.Color(0, 153, 0));
        Input_fibo.setToolTipText("");
        Input_fibo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Input_fibo.setSelectionColor(new java.awt.Color(60, 63, 65));

        B_salir.setBackground(new java.awt.Color(57, 248, 250));
        B_salir.setForeground(new java.awt.Color(0, 153, 0));
        B_salir.setText("Salir");
        B_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salir(evt);
            }
        });

        Generar_serie.setBackground(new java.awt.Color(57, 248, 250));
        Generar_serie.setForeground(new java.awt.Color(0, 153, 0));
        Generar_serie.setText("Generar serie");
        Generar_serie.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Generar_serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generar_serie(evt);
            }
        });

        B_limp_pant.setBackground(new java.awt.Color(57, 248, 250));
        B_limp_pant.setForeground(new java.awt.Color(0, 153, 0));
        B_limp_pant.setText("Limpiar pantalla");
        B_limp_pant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_limp_pant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lim_pant(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("en un intervalo del 1 al 46");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(182, 182, 182))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(B_limp_pant, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(B_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Generar_serie, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Input_fibo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(132, 132, 132))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(17, 17, 17)
                        .addComponent(Input_fibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(Generar_serie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(B_salir)
                            .addComponent(B_limp_pant)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jMenu1.setText("Primer parcial");
        jMenu1.setToolTipText("Ejercicios de áreas, magnitudes, otros.");

        jMenu4.setText("Calcular áreas");

        jMenuItem4.setText("Área del circulo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Circulo(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Área del rectángulo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rectangulo(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem6.setText("Área del trapecio");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trapecio(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem3.setText("Área del triángulo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Triaangulo(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);

        jMenu6.setText("Magnitides Físicas");

        jMenuItem8.setText("Densidad");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Densidad(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem9.setText("Masa");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masa(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem7.setText("Volumen");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volumen(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenu1.add(jMenu6);

        jMenu7.setText("Calcular áreas");

        jMenuItem10.setText("Fórmula cuadrática");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Formula_cuadratica(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenu1.add(jMenu7);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Segundo parcial");
        jMenu2.setToolTipText("Ejercicios condisonales: if, switch, repetitivas.");

        jMenu9.setText("Condisional if");

        jMenuItem11.setText("Calcular edad");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_edad(evt);
            }
        });
        jMenu9.add(jMenuItem11);

        jMenuItem14.setText("Producto");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productos(evt);
            }
        });
        jMenu9.add(jMenuItem14);

        jMenuItem16.setText("Promedio");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promedio(evt);
            }
        });
        jMenu9.add(jMenuItem16);

        jMenuItem15.setText("Verificar números pares");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Verificar_par(evt);
            }
        });
        jMenu9.add(jMenuItem15);

        jMenuItem13.setText("viajes");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Viajes(evt);
            }
        });
        jMenu9.add(jMenuItem13);

        jMenu2.add(jMenu9);

        jMenu10.setText("Estructura / switch");

        jMenuItem18.setText("Calculadora");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculadora(evt);
            }
        });
        jMenu10.add(jMenuItem18);

        jMenuItem20.setText("Menú áreas");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_areas(evt);
            }
        });
        jMenu10.add(jMenuItem20);

        jMenu2.add(jMenu10);

        jMenu8.setText("Estructuras de control iterativas");

        jMenu11.setText("Bucle for");

        jMenuItem22.setText("Lista de Números");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_numeros(evt);
            }
        });
        jMenu11.add(jMenuItem22);

        jMenuItem24.setText("Numeración");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numeracion(evt);
            }
        });
        jMenu11.add(jMenuItem24);

        jMenuItem23.setText("Tabla del siete");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablas_del_siete(evt);
            }
        });
        jMenu11.add(jMenuItem23);

        jMenuItem21.setText("Tablas de multiplicar");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tablas_de_multiplicar(evt);
            }
        });
        jMenu11.add(jMenuItem21);

        jMenu8.add(jMenu11);

        jMenu13.setText("Bucle while");

        jMenuItem26.setText("Contar hasta N / Mostrar texto");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contar_mostrar_texto(evt);
            }
        });
        jMenu13.add(jMenuItem26);

        jMenuItem25.setText("Suma de números");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sumas_while(evt);
            }
        });
        jMenu13.add(jMenuItem25);

        jMenu8.add(jMenu13);

        jMenu12.setText("Bucle do while");
        jMenu8.add(jMenu12);

        jMenu2.add(jMenu8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Menú principal");
        jMenu3.setToolTipText("Regresar al menú principal.");

        jMenuItem2.setText("Menu inicio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_inicio(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Generar_serie(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generar_serie
        int anterior = 0;
        int actual = 1;
        int nuevo;
        int numero_usu = Integer.parseInt(Input_fibo.getText());
        int i = 0;

        area_texto.setText("");

        if (numero_usu >= 1 && numero_usu <= 46) {

            while (i <= numero_usu) {
                area_texto.append("\n" + anterior);
                nuevo = anterior + actual;
                anterior = actual;
                actual = nuevo;
                i++;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Los valores no son del rango sugerido.");
        }


    }//GEN-LAST:event_Generar_serie

    private void Lim_pant(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lim_pant
        area_texto.setText("");
        Input_fibo.setText("");
    }//GEN-LAST:event_Lim_pant

    private void Salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salir
        dispose();
    }//GEN-LAST:event_Salir

    private void Circulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Circulo
        int_graf_circ ventana_1 = new int_graf_circ();
        ventana_1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Circulo

    private void Rectangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rectangulo
        Interfaz_grafica_Rec ventana_2 = new Interfaz_grafica_Rec();
        ventana_2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Rectangulo

    private void Trapecio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trapecio
        Int_graf_trap ventana_3 = new Int_graf_trap();
        ventana_3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Trapecio

    private void Triaangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Triaangulo
        Interfaz_grafica_Tri ventana_4 = new Interfaz_grafica_Tri();
        ventana_4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Triaangulo

    private void Densidad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Densidad
        Int_graf_densidad ventana_5 = new Int_graf_densidad();
        ventana_5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Densidad

    private void Masa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masa
        Int_graf_Masa ventana_6 = new Int_graf_Masa();
        ventana_6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Masa

    private void Volumen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volumen
        int_graf_volumen ventana_7 = new int_graf_volumen();
        ventana_7.setVisible(true);
        this.dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_Volumen

    private void Formula_cuadratica(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Formula_cuadratica
        int_graf_formula_cu ventana_8 = new int_graf_formula_cu();
        ventana_8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Formula_cuadratica

    private void calc_edad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_edad
        Int_graf_calc_edad ventana_9 = new Int_graf_calc_edad();
        ventana_9.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calc_edad

    private void Productos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productos
        int_graf_produc ventana_10 = new int_graf_produc();
        ventana_10.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Productos

    private void promedio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promedio
        calc_calif ventana_11 = new calc_calif();
        ventana_11.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_promedio

    private void Verificar_par(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Verificar_par
        Int_graf_numero_par ventana_12 = new Int_graf_numero_par();
        ventana_12.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Verificar_par

    private void Viajes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Viajes
        Int_graf_viajes ventana_13 = new Int_graf_viajes();
        ventana_13.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Viajes

    private void Calculadora(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculadora
        Int_graf_calculadora ventana_14 = new Int_graf_calculadora();
        ventana_14.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Calculadora

    private void menu_areas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_areas
        mini_menu_areas ventana_15 = new mini_menu_areas();
        ventana_15.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_areas

    private void Lista_numeros(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_numeros
        int_graf_lista_num ventana_16 = new int_graf_lista_num();
        ventana_16.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Lista_numeros

    private void Numeracion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numeracion
        int_graf_num_10_20 ventana_17 = new int_graf_num_10_20();
        ventana_17.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Numeracion

    private void tablas_del_siete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablas_del_siete
        Tabla_del_siete ventana_18 = new Tabla_del_siete();
        ventana_18.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tablas_del_siete

    private void tablas_de_multiplicar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablas_de_multiplicar
        int_graf_tablas ventana_19 = new int_graf_tablas();
        ventana_19.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tablas_de_multiplicar

    private void Contar_mostrar_texto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contar_mostrar_texto
        int_grafi_while ventana_20 = new int_grafi_while();
        ventana_20.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Contar_mostrar_texto

    private void Sumas_while(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sumas_while
        Int_graf_suma_while ventana_21 = new Int_graf_suma_while();
        ventana_21.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Sumas_while

    private void Menu_inicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_inicio
        Menu_gui ventana_22 = new Menu_gui();
        ventana_22.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_inicio

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(int_graf_fibonacci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(int_graf_fibonacci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(int_graf_fibonacci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(int_graf_fibonacci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new int_graf_fibonacci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_limp_pant;
    private javax.swing.JButton B_salir;
    private javax.swing.JButton Generar_serie;
    private javax.swing.JTextField Input_fibo;
    private javax.swing.JTextArea area_texto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
