/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerardo_martinez.mavenproject1;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Gerry-Mel
 */
public class int_graf_tablas extends javax.swing.JFrame {

    /**
     * Creates new form int_graf_tablas
     */
    public int_graf_tablas() {
        initComponents();
    }

    public class PanelDegradado extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g;

            GradientPaint gp = new GradientPaint(
                    0, 0, new Color(255, 153, 0),
                    0, getHeight(), new Color(237, 36, 0)
            );

            g2.setPaint(gp);
            g2.fillRect(0, 0, getWidth(), getHeight());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jPanel1 = new PanelDegradado();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Lista_tablas = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area_texto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu5.setText("jMenu5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setBackground(new java.awt.Color(255, 157, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 204));
        jButton2.setText("Salir");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_salir(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 157, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 204));
        jButton1.setText("Limpiar pantalla");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_limpiar(evt);
            }
        });

        Lista_tablas.setBackground(new java.awt.Color(255, 157, 0));
        Lista_tablas.setForeground(new java.awt.Color(255, 255, 204));
        Lista_tablas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tabla de multiplicar:", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        Lista_tablas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Lista_tablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_tablas(evt);
            }
        });

        jScrollPane1.setHorizontalScrollBar(null);

        Area_texto.setEditable(false);
        Area_texto.setBackground(new java.awt.Color(255, 157, 0));
        Area_texto.setColumns(20);
        Area_texto.setForeground(new java.awt.Color(255, 255, 204));
        Area_texto.setRows(5);
        Area_texto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Area_texto.setFocusable(false);
        Area_texto.setPreferredSize(new java.awt.Dimension(224, 84));
        Area_texto.setRequestFocusEnabled(false);
        Area_texto.setSelectionColor(new java.awt.Color(30, 30, 30));
        jScrollPane1.setViewportView(Area_texto);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("Selecciona una tabla de multiplicar");

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("Tablas de multiplicar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(Lista_tablas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(80, 80, 80))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Lista_tablas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jMenu1.setText("Primer parcial");
        jMenu1.setToolTipText("Ejercicios de áreas, magnitudes, otros.");

        jMenu6.setText("Calcular áreas");

        jMenuItem15.setText("Área del circulo");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Circulo(evt);
            }
        });
        jMenu6.add(jMenuItem15);

        jMenuItem18.setText("Área del rectángulo");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rectangulo(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem17.setText("Área del trapecio");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trapecio(evt);
            }
        });
        jMenu6.add(jMenuItem17);

        jMenuItem16.setText("Área del triángulo");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Triangulo(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenu1.add(jMenu6);

        jMenu7.setText("Magnitides Físicas");

        jMenuItem19.setText("Densidad");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Densidad(evt);
            }
        });
        jMenu7.add(jMenuItem19);

        jMenuItem21.setText("Masa");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masa(evt);
            }
        });
        jMenu7.add(jMenuItem21);

        jMenuItem20.setText("Volumen");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volumen(evt);
            }
        });
        jMenu7.add(jMenuItem20);

        jMenu1.add(jMenu7);

        jMenu4.setText("Otros ejercicios");

        jMenuItem22.setText("Fórmula cuadrática");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Formula_cua(evt);
            }
        });
        jMenu4.add(jMenuItem22);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Segundo parcial");
        jMenu2.setToolTipText("Ejercicios condisonales: if, switch, repetitivas.");

        jMenu8.setText("Condisional if");

        jMenuItem2.setText("Calcular edad");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_edad(evt);
            }
        });
        jMenu8.add(jMenuItem2);

        jMenuItem8.setText("Productos");
        jMenuItem8.setToolTipText("");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productos(evt);
            }
        });
        jMenu8.add(jMenuItem8);

        jMenuItem5.setText("Promedio");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Promedio(evt);
            }
        });
        jMenu8.add(jMenuItem5);

        jMenuItem4.setText("Verificar números pares");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_par(evt);
            }
        });
        jMenu8.add(jMenuItem4);

        jMenuItem3.setText("Viajes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Viajes(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenu2.add(jMenu8);

        jMenu9.setText("Estructura / switch");

        jMenuItem9.setText("Calculadora");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculadora(evt);
            }
        });
        jMenu9.add(jMenuItem9);

        jMenuItem10.setText("Menú áreas");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_areas(evt);
            }
        });
        jMenu9.add(jMenuItem10);

        jMenu2.add(jMenu9);

        jMenu10.setText("Estructuras de control iterativas");

        jMenu12.setText("Bucle for");

        jMenuItem12.setText("Lista de Números");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_num(evt);
            }
        });
        jMenu12.add(jMenuItem12);

        jMenuItem14.setText("Numeración");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numeracion(evt);
            }
        });
        jMenu12.add(jMenuItem14);

        jMenuItem13.setText("Tabla del siete");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tabla_siete(evt);
            }
        });
        jMenu12.add(jMenuItem13);

        jMenu10.add(jMenu12);

        jMenu13.setText("Bucle while");

        jMenuItem23.setText("Contar hasta N / Mostrar texto");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contar_mostrar_texto(evt);
            }
        });
        jMenu13.add(jMenuItem23);

        jMenuItem24.setText("Suma de números");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suma_while(evt);
            }
        });
        jMenu13.add(jMenuItem24);

        jMenuItem11.setText("Sucesión Fibonacci");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucesion_fibonacci(evt);
            }
        });
        jMenu13.add(jMenuItem11);

        jMenu10.add(jMenu13);

        jMenu11.setText("Bucle do while");
        jMenu10.add(jMenu11);

        jMenu2.add(jMenu10);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Menú principal");
        jMenu3.setToolTipText("Regresar al menú principal.");

        jMenuItem1.setText("Menú inicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_inicio(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lista_tablas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_tablas

        int seleccion = Integer.parseInt(Lista_tablas.getSelectedItem().toString());

        switch (seleccion) {
            case 1:
                Area_texto.setText("");
                for (int i = 1; i <= 10; i++) {
                    Area_texto.append("1 x " + i + " = " + (i * 1) + "\n");
                }
                break;
            case 2:
                Area_texto.setText("");
                for (int i = 1; i <= 10; i++) {
                    Area_texto.append("2 x " + i + " = " + (i * 2) + "\n");
                }
                break;
            case 3:
                Area_texto.setText("");
                for (int i = 1; i <= 10; i++) {
                    Area_texto.append("3 x " + i + " = " + (i * 3) + "\n");
                }
                break;
            case 4:
                Area_texto.setText("");
                for (int i = 1; i <= 10; i++) {
                    Area_texto.append("4 x " + i + " = " + (i * 4) + "\n");
                }
                break;
            case 5:
                Area_texto.setText("");
                for (int i = 1; i <= 10; i++) {
                    Area_texto.append("5 x " + i + " = " + (i * 5) + "\n");
                }
                break;
            case 6:
                Area_texto.setText("");
                for (int i = 1; i <= 10; i++) {
                    Area_texto.append("6 x " + i + " = " + (i * 6) + "\n");
                }
                break;
            case 7:
                Area_texto.setText("");
                for (int i = 1; i <= 10; i++) {
                    Area_texto.append("7 x " + i + " = " + (i * 7) + "\n");
                }
                break;
            case 8:
                Area_texto.setText("");
                for (int i = 1; i <= 10; i++) {
                    Area_texto.append("8 x " + i + " = " + (i * 8) + "\n");
                }
                break;
            case 9:
                Area_texto.setText("");
                for (int i = 1; i <= 10; i++) {
                    Area_texto.append("9 x " + i + " = " + (i * 9) + "\n");
                }
                break;
            case 10:
                Area_texto.setText("");
                for (int i = 1; i <= 10; i++) {
                    Area_texto.append("10 x " + i + " = " + (i * 10) + "\n");
                }
                break;
        }
    }//GEN-LAST:event_lista_tablas

    private void B_limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_limpiar
        Area_texto.setText("");
    }//GEN-LAST:event_B_limpiar

    private void B_salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_salir
        dispose();
    }//GEN-LAST:event_B_salir

    private void Circulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Circulo
        int_graf_circ ventana_1 = new int_graf_circ();
        ventana_1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Circulo

    private void Rectangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rectangulo
        Interfaz_grafica_Rec ventana_2 = new Interfaz_grafica_Rec();
        ventana_2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Rectangulo

    private void trapecio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trapecio
        Int_graf_trap ventana_3 = new Int_graf_trap();
        ventana_3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trapecio

    private void Triangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Triangulo
        Interfaz_grafica_Tri ventana_4 = new Interfaz_grafica_Tri();
        ventana_4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Triangulo

    private void Densidad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Densidad
        Int_graf_densidad ventana_5 = new Int_graf_densidad();
        ventana_5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Densidad

    private void Masa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masa
        Int_graf_Masa ventana_6 = new Int_graf_Masa();
        ventana_6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Masa

    private void Volumen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volumen
        int_graf_volumen ventana_7 = new int_graf_volumen();
        ventana_7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Volumen

    private void Formula_cua(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Formula_cua
        int_graf_formula_cu ventana_8 = new int_graf_formula_cu();
        ventana_8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Formula_cua

    private void calc_edad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_edad
        Int_graf_calc_edad ventana_9 = new Int_graf_calc_edad();
        ventana_9.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calc_edad

    private void Productos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productos
        int_graf_produc ventana_12 = new int_graf_produc();
        ventana_12.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Productos

    private void Promedio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Promedio
        calc_calif ventana_13 = new calc_calif();
        ventana_13.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Promedio

    private void Ver_par(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_par
        Int_graf_numero_par ventana_10 = new Int_graf_numero_par();
        ventana_10.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ver_par

    private void Viajes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Viajes
        Int_graf_viajes ventana_11 = new Int_graf_viajes();
        ventana_11.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Viajes

    private void Calculadora(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculadora
        Int_graf_calculadora ventana_14 = new Int_graf_calculadora();
        ventana_14.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Calculadora

    private void Menu_areas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_areas
        mini_menu_areas ventana_15 = new mini_menu_areas();
        ventana_15.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_areas

    private void list_num(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_num
        int_graf_lista_num ventana_16 = new int_graf_lista_num();
        ventana_16.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_list_num

    private void Numeracion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numeracion
        int_graf_num_10_20 ventana_17 = new int_graf_num_10_20();
        ventana_17.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Numeracion

    private void Tabla_siete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tabla_siete
        Tabla_del_siete ventana_18 = new Tabla_del_siete();
        ventana_18.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Tabla_siete

    private void Menu_inicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_inicio
        Menu_gui ventana_19 = new Menu_gui();
        ventana_19.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_inicio

    private void contar_mostrar_texto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contar_mostrar_texto
        int_grafi_while ventana_20 = new int_grafi_while();
        ventana_20.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_contar_mostrar_texto

    private void suma_while(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suma_while
        Int_graf_suma_while ventana_21 = new Int_graf_suma_while();
        ventana_21.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_suma_while

    private void sucesion_fibonacci(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucesion_fibonacci
        int_graf_fibonacci ventana_22 = new int_graf_fibonacci();
        ventana_22.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sucesion_fibonacci

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(int_graf_tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(int_graf_tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(int_graf_tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(int_graf_tablas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new int_graf_tablas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area_texto;
    private javax.swing.JComboBox<String> Lista_tablas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
