/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerardo_martinez.mavenproject1;

import javax.swing.JOptionPane;

/**
 *
 * @author Gerry-Mel
 */
public class int_graf_formula_cu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(int_graf_formula_cu.class.getName());

    /**
     * Creates new form int_graf_formual_cu
     */
    public int_graf_formula_cu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Input_coe_c = new javax.swing.JTextField();
        Input_coe_b = new javax.swing.JTextField();
        Input_coe_a = new javax.swing.JTextField();
        B_limp_camp = new javax.swing.JButton();
        B_calcular_ecu = new javax.swing.JButton();
        B_salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Calculadora de  raíces");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Ingresa el valor del coeficiente de A");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Ingrea el valor del coefiencte de B");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Ingresa el valor C");

        Input_coe_c.setBackground(new java.awt.Color(255, 51, 51));
        Input_coe_c.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), null));
        Input_coe_c.addActionListener(this::Input_coe_c);

        Input_coe_b.setBackground(new java.awt.Color(255, 51, 51));
        Input_coe_b.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), null));
        Input_coe_b.addActionListener(this::Input_coe_b);

        Input_coe_a.setBackground(new java.awt.Color(255, 51, 51));
        Input_coe_a.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 153, 153), null));
        Input_coe_a.addActionListener(this::Input_coe_a);

        B_limp_camp.setBackground(new java.awt.Color(204, 0, 0));
        B_limp_camp.setForeground(new java.awt.Color(255, 153, 153));
        B_limp_camp.setText("Limpiar campos");
        B_limp_camp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_limp_camp.addActionListener(this::B_limp_camp);

        B_calcular_ecu.setBackground(new java.awt.Color(153, 0, 0));
        B_calcular_ecu.setForeground(new java.awt.Color(255, 153, 153));
        B_calcular_ecu.setText("Calcular  ecuacion");
        B_calcular_ecu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_calcular_ecu.addActionListener(this::B_calcular_ecu);

        B_salir.setBackground(new java.awt.Color(204, 0, 0));
        B_salir.setForeground(new java.awt.Color(255, 153, 153));
        B_salir.setText("Salir");
        B_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_salir.addActionListener(this::B_salir);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("ecuacuión: ax^2 +bx + c = 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(B_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(B_calcular_ecu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(B_limp_camp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Input_coe_c, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Input_coe_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Input_coe_a, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Input_coe_a, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Input_coe_b, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Input_coe_c, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_calcular_ecu)
                    .addComponent(B_salir)
                    .addComponent(B_limp_camp))
                .addGap(55, 55, 55))
        );

        jMenu1.setText("Primer parcial");
        jMenu1.setToolTipText("Ejercicios de áreas, magnitudes, otros.");

        jMenu4.setText("Calcular áreas");

        jMenuItem2.setText("Área del circulo");
        jMenuItem2.addActionListener(this::Area_circulo);
        jMenu4.add(jMenuItem2);

        jMenuItem4.setText("Área del rectángulo");
        jMenuItem4.addActionListener(this::Rectangulo);
        jMenu4.add(jMenuItem4);

        jMenuItem7.setText("Área del trapecio");
        jMenuItem7.addActionListener(this::Trapecio);
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Área del triángulo");
        jMenuItem8.addActionListener(this::Triangulo);
        jMenu4.add(jMenuItem8);

        jMenu1.add(jMenu4);

        jMenu5.setText("Magnitides Físicas");

        jMenuItem6.setText("Densidad");
        jMenuItem6.addActionListener(this::Densidad);
        jMenu5.add(jMenuItem6);

        jMenuItem5.setText("Masa");
        jMenuItem5.addActionListener(this::Masa);
        jMenu5.add(jMenuItem5);

        jMenuItem3.setText("Volumen");
        jMenuItem3.addActionListener(this::Volumen);
        jMenu5.add(jMenuItem3);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Segundo parcial");
        jMenu2.setToolTipText("Ejercicios condisonales: if, switch, repetitivas.");

        jMenu6.setText("Condisional if");

        jMenuItem10.setText("Calcular edad");
        jMenuItem10.addActionListener(this::Calc_edad);
        jMenu6.add(jMenuItem10);

        jMenuItem13.setText("Producto");
        jMenuItem13.addActionListener(this::Producto);
        jMenu6.add(jMenuItem13);

        jMenuItem11.setText("Promedio");
        jMenuItem11.addActionListener(this::Promedio);
        jMenu6.add(jMenuItem11);

        jMenuItem12.setText("Verificar números pares");
        jMenuItem12.addActionListener(this::Ver_par);
        jMenu6.add(jMenuItem12);

        jMenuItem9.setText("viajes");
        jMenuItem9.addActionListener(this::Viajes);
        jMenu6.add(jMenuItem9);

        jMenu2.add(jMenu6);

        jMenu7.setText("Estructura / switch");

        jMenuItem14.setText("Calculadora");
        jMenuItem14.addActionListener(this::Calculadora);
        jMenu7.add(jMenuItem14);

        jMenuItem15.setText("Menú áreas");
        jMenuItem15.addActionListener(this::menu_areas);
        jMenu7.add(jMenuItem15);

        jMenu2.add(jMenu7);

        jMenu8.setText("Estructuras de control iterativas");

        jMenu9.setText("Bucle for ");

        jMenuItem16.setText("Lista de Números");
        jMenuItem16.addActionListener(this::List_num);
        jMenu9.add(jMenuItem16);

        jMenuItem19.setText("Numeración");
        jMenuItem19.addActionListener(this::numeracion);
        jMenu9.add(jMenuItem19);

        jMenuItem18.setText("Tabla del siete");
        jMenuItem18.addActionListener(this::tabla_siete);
        jMenu9.add(jMenuItem18);

        jMenuItem17.setText("Tablas de multiplicar");
        jMenuItem17.addActionListener(this::tablas_mulit);
        jMenu9.add(jMenuItem17);

        jMenu8.add(jMenu9);

        jMenu10.setText("Bucle while ");

        jMenuItem21.setText("Contar hasta N / Mostrar texto");
        jMenuItem21.addActionListener(this::contar_mostrar_texto);
        jMenu10.add(jMenuItem21);

        jMenuItem20.setText("Suma de números");
        jMenuItem20.addActionListener(this::suma_while);
        jMenu10.add(jMenuItem20);

        jMenuItem22.setText("Sucesión Fibonacci");
        jMenuItem22.addActionListener(this::sucesion_fibonacci);
        jMenu10.add(jMenuItem22);

        jMenu8.add(jMenu10);

        jMenu11.setText("Bucle do while ");
        jMenu8.add(jMenu11);

        jMenu2.add(jMenu8);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Menú inicio");
        jMenu3.setToolTipText("Regresar al menú principal.");

        jMenuItem1.setText("Menu inicio");
        jMenuItem1.addActionListener(this::Menu_inicio);
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Input_coe_b(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_coe_b
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_coe_b

    private void Input_coe_a(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_coe_a
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_coe_a

    private void Input_coe_c(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Input_coe_c
        // TODO add your handling code here:
    }//GEN-LAST:event_Input_coe_c

    private void B_calcular_ecu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_calcular_ecu

        int coe_a, coe_b, coe_c;//coeficientes de la ecuacion
        double raiz_p, raiz_n;//raiz positiva (p) y raiz negativa (n).
        coe_a = Integer.parseInt(Input_coe_a.getText());
        coe_b = Integer.parseInt(Input_coe_b.getText());
        coe_c = Integer.parseInt(Input_coe_c.getText());

        raiz_p = (-coe_b + Math.sqrt(Math.pow(coe_b, 2) - 4 * coe_a * coe_c)) / (2 * coe_a);
        raiz_n = (-coe_b - Math.sqrt(Math.pow(coe_b, 2) - 4 * coe_a * coe_c)) / (2 * coe_a);

        JOptionPane.showMessageDialog(null, "La raiz positiva es: " + raiz_p + "\n La raiz Negativa es" + raiz_n);


    }//GEN-LAST:event_B_calcular_ecu

    private void B_limp_camp(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_limp_camp
        Input_coe_a.setText("");
        Input_coe_b.setText("");
        Input_coe_c.setText("");
    }//GEN-LAST:event_B_limp_camp

    private void B_salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_salir
        dispose();
    }//GEN-LAST:event_B_salir

    private void Menu_inicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_inicio
        Menu_gui ventana_1 = new Menu_gui();
        ventana_1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_inicio

    private void Area_circulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Area_circulo
        int_graf_circ ventana_2 = new int_graf_circ();
        ventana_2.setVisible(true);
    }//GEN-LAST:event_Area_circulo

    private void Rectangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rectangulo
        Interfaz_grafica_Rec ventana_3 = new Interfaz_grafica_Rec();
        ventana_3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Rectangulo

    private void Trapecio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trapecio
        Int_graf_trap ventana_4 = new Int_graf_trap();
        ventana_4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Trapecio

    private void Triangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Triangulo
        Interfaz_grafica_Tri ventana_5 = new Interfaz_grafica_Tri();
        ventana_5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Triangulo

    private void Densidad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Densidad
        Int_graf_densidad ventana_6 = new Int_graf_densidad();
        ventana_6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Densidad

    private void Masa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masa
        Int_graf_Masa ventana_7 = new Int_graf_Masa();
        ventana_7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Masa

    private void Volumen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volumen
        int_graf_volumen ventana_8 = new int_graf_volumen();
        ventana_8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Volumen

    private void Calc_edad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc_edad
        Int_graf_calc_edad ventana_9 = new Int_graf_calc_edad();
        ventana_9.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Calc_edad

    private void Producto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Producto
        int_graf_produc ventana_10 = new int_graf_produc();
        ventana_10.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Producto

    private void Promedio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Promedio
        calc_calif ventana_11 = new calc_calif();
        ventana_11.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Promedio

    private void Ver_par(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_par
        Int_graf_numero_par ventana_12 = new Int_graf_numero_par();
        ventana_12.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Ver_par

    private void Viajes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Viajes
        Int_graf_viajes ventana_13 = new Int_graf_viajes();
        ventana_13.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Viajes

    private void Calculadora(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculadora
        Int_graf_calculadora ventana_14 = new Int_graf_calculadora();
        ventana_14.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Calculadora

    private void menu_areas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_areas
        mini_menu_areas ventana_15 = new mini_menu_areas();
        ventana_15.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_areas

    private void List_num(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_List_num
        int_graf_lista_num ventana_16 = new int_graf_lista_num();
        ventana_16.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_List_num

    private void numeracion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeracion
        int_graf_num_10_20 ventana_17 = new int_graf_num_10_20();
        ventana_17.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_numeracion

    private void tabla_siete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabla_siete
        Tabla_del_siete ventana_18 = new Tabla_del_siete();
        ventana_18.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tabla_siete

    private void tablas_mulit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tablas_mulit
        int_graf_tablas ventana_19 = new int_graf_tablas();
        ventana_19.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tablas_mulit

    private void contar_mostrar_texto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contar_mostrar_texto
        int_grafi_while ventana_20 = new int_grafi_while();
        ventana_20.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_contar_mostrar_texto

    private void suma_while(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suma_while
        Int_graf_suma_while ventana_21 = new Int_graf_suma_while();
        ventana_21.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_suma_while

    private void sucesion_fibonacci(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucesion_fibonacci
        int_graf_fibonacci ventana_22 = new int_graf_fibonacci();
        ventana_22.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sucesion_fibonacci

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new int_graf_formula_cu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_calcular_ecu;
    private javax.swing.JButton B_limp_camp;
    private javax.swing.JButton B_salir;
    private javax.swing.JTextField Input_coe_a;
    private javax.swing.JTextField Input_coe_b;
    private javax.swing.JTextField Input_coe_c;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
