/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerardo_martinez.mavenproject1;

import javax.swing.JOptionPane;
import javax.swing.*;
import java.awt.*;
import java.awt.Color;

/**
 *
 * @author Gerry-Mel
 */
public class Int_graf_calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Int_graf_calculadora
     */
    public Int_graf_calculadora() {
        initComponents();
        Input_num_2.setCaretColor(Color.decode("#1111"));
    }

    public class PanelDegradado extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g;

            GradientPaint gp = new GradientPaint(
                    0, 0, new Color(102, 0, 51),
                    0, getHeight(), new Color(153, 0, 76)
            );

            g2.setPaint(gp);
            g2.fillRect(0, 0, getWidth(), getHeight());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu11 = new javax.swing.JMenu();
        jMenu14 = new javax.swing.JMenu();
        Jpanel = new PanelDegradado();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Input_num_2 = new javax.swing.JTextField();
        Input_num_1 = new javax.swing.JTextField();
        Input_resultado = new javax.swing.JTextField();
        Lista_operaciones = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        B_limpiar = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();

        jMenu11.setText("jMenu11");

        jMenu14.setText("jMenu14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Jpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Operador de números ");
        Jpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("Ingresa el primer número:");
        Jpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 180, 20));

        Input_num_2.setBackground(new java.awt.Color(255, 102, 102));
        Input_num_2.setForeground(new java.awt.Color(153, 0, 0));
        Input_num_2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input_num_2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Jpanel.add(Input_num_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 130, -1));

        Input_num_1.setBackground(new java.awt.Color(255, 102, 102));
        Input_num_1.setForeground(new java.awt.Color(153, 0, 0));
        Input_num_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input_num_1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Jpanel.add(Input_num_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 130, -1));

        Input_resultado.setEditable(false);
        Input_resultado.setBackground(new java.awt.Color(255, 102, 102));
        Input_resultado.setForeground(new java.awt.Color(153, 0, 0));
        Input_resultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Input_resultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Input_resultado.setFocusable(false);
        Jpanel.add(Input_resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 130, -1));

        Lista_operaciones.setBackground(new java.awt.Color(255, 102, 102));
        Lista_operaciones.setForeground(new java.awt.Color(102, 0, 0));
        Lista_operaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lista de operaciones", "suma", "resta", "división", "multiplicación" }));
        Lista_operaciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Lista_operaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_operaciones(evt);
            }
        });
        Jpanel.add(Lista_operaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("Resultado:");
        Jpanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 70, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("Ingresa el segundo número:");
        Jpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 170, -1));

        B_limpiar.setBackground(new java.awt.Color(255, 102, 102));
        B_limpiar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        B_limpiar.setForeground(new java.awt.Color(102, 0, 0));
        B_limpiar.setText("Limpiar Campos");
        B_limpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_limpiar(evt);
            }
        });
        Jpanel.add(B_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 30));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Operador de números ");
        Jpanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jToggleButton1.setBackground(new java.awt.Color(255, 102, 102));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(102, 0, 0));
        jToggleButton1.setText("Salir");
        jToggleButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_salir(evt);
            }
        });
        Jpanel.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 90, -1));

        jMenu1.setText("Primer parcial");
        jMenu1.setToolTipText("Ejercicios de áreas, magnitudes, otros.");

        jMenu4.setText("Calcular áreas");

        jMenuItem4.setText("Área del circulo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_circulo(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem1.setText("Área del rectángulo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rectangulo(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Área del trapecio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trapecio(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Área del tríangulo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Triangulo(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenu1.add(jMenu4);

        jMenu5.setText("Magnitides Físicas");

        jMenuItem5.setText("Densidad");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Densidad(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setText("Masa");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masa(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuItem7.setText("Volumen");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volumen(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenu1.add(jMenu5);

        jMenu6.setText("Otros ejercicios");

        jMenuItem8.setText("Fórmla cuadrática");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Formula_cua(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Segundo parcial");
        jMenu2.setToolTipText("Ejercicios condisonales: if, switch, repetitivas.");

        jMenu7.setText("Condisional if");
        jMenu7.setToolTipText("");

        jMenuItem9.setText("Calcular edad");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calcular_edad(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuItem10.setText("Productos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Producto(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenuItem13.setText("Promedio");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Promedio(evt);
            }
        });
        jMenu7.add(jMenuItem13);

        jMenuItem12.setText("Verificar números pares");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pares(evt);
            }
        });
        jMenu7.add(jMenuItem12);

        jMenuItem11.setText("Viajes");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Viajes(evt);
            }
        });
        jMenu7.add(jMenuItem11);

        jMenu2.add(jMenu7);

        jMenu8.setText("Estructura  / switch");

        jMenuItem15.setText("Menú áreas");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_areas(evt);
            }
        });
        jMenu8.add(jMenuItem15);

        jMenu2.add(jMenu8);

        jMenu9.setText("Estructuras de control iterativas");

        jMenu10.setText("Bucle for");

        jMenuItem16.setText("Lista de Números");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_num(evt);
            }
        });
        jMenu10.add(jMenuItem16);

        jMenuItem19.setText("Numeración");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numeracion(evt);
            }
        });
        jMenu10.add(jMenuItem19);

        jMenuItem18.setText("Tabla del siete");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tabla_siete(evt);
            }
        });
        jMenu10.add(jMenuItem18);

        jMenuItem17.setText("Tablas de multiplicar");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tablas_multi(evt);
            }
        });
        jMenu10.add(jMenuItem17);

        jMenu9.add(jMenu10);

        jMenu12.setText("Bucle while");

        jMenuItem20.setText("Contar hasta N / Mostrar texto");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contar_mostrar_texto(evt);
            }
        });
        jMenu12.add(jMenuItem20);

        jMenuItem22.setText("Suma de números");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumas_con_while(evt);
            }
        });
        jMenu12.add(jMenuItem22);

        jMenuItem21.setText("Sucesión Fibonacci");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sucesion_Fibonacci(evt);
            }
        });
        jMenu12.add(jMenuItem21);

        jMenu9.add(jMenu12);

        jMenu13.setText("Bucle do while");
        jMenu9.add(jMenu13);

        jMenu2.add(jMenu9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Menú inicio");
        jMenu3.setToolTipText("Regresar al menú principal.");

        jMenuItem14.setText("Menú inicio ");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void A_circulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_circulo
        int_graf_circ ventana_1 = new int_graf_circ();
        ventana_1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_A_circulo

    private void Rectangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rectangulo
        Interfaz_grafica_Rec ventana_2 = new Interfaz_grafica_Rec();
        ventana_2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Rectangulo

    private void trapecio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trapecio
        Int_graf_trap ventana_3 = new Int_graf_trap();
        ventana_3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trapecio

    private void Triangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Triangulo
        Interfaz_grafica_Tri ventana_4 = new Interfaz_grafica_Tri();
        ventana_4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Triangulo

    private void Densidad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Densidad
        Int_graf_densidad ventana_5 = new Int_graf_densidad();
        ventana_5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Densidad

    private void Masa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masa
        Int_graf_Masa ventana_6 = new Int_graf_Masa();
        ventana_6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Masa

    private void Volumen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volumen
        int_graf_volumen ventana_7 = new int_graf_volumen();
        ventana_7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Volumen

    private void Formula_cua(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Formula_cua
        int_graf_formula_cu ventana_8 = new int_graf_formula_cu();
        ventana_8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Formula_cua

    private void Calcular_edad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calcular_edad
        Int_graf_calc_edad ventana_10 = new Int_graf_calc_edad();
        ventana_10.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Calcular_edad

    private void Producto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Producto
        int_graf_produc ventana_11 = new int_graf_produc();
        ventana_11.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Producto

    private void Promedio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Promedio
        calc_calif ventana_12 = new calc_calif();
        ventana_12.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Promedio

    private void Pares(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pares
        Int_graf_numero_par ventana_13 = new Int_graf_numero_par();
        ventana_13.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_Pares

    private void Viajes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Viajes
        Int_graf_viajes ventana_14 = new Int_graf_viajes();
        ventana_14.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Viajes

    private void Menu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu
        Menu_gui ventana_15 = new Menu_gui();
        ventana_15.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu

    private void menu_areas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_areas
        mini_menu_areas ventana_16 = new mini_menu_areas();
        ventana_16.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_areas

    private void list_num(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_num
        int_graf_lista_num ventana_17 = new int_graf_lista_num();
        ventana_17.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_list_num

    private void Numeracion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numeracion
        int_graf_num_10_20 ventana_18 = new int_graf_num_10_20();
        ventana_18.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Numeracion

    private void Tabla_siete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tabla_siete
        Tabla_del_siete ventana_19 = new Tabla_del_siete();
        ventana_19.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Tabla_siete

    private void Tablas_multi(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tablas_multi
        int_graf_tablas ventana_20 = new int_graf_tablas();
        ventana_20.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Tablas_multi

    private void contar_mostrar_texto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contar_mostrar_texto
        int_grafi_while ventana_21 = new int_grafi_while();
        ventana_21.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_contar_mostrar_texto

    private void sumas_con_while(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumas_con_while
        Int_graf_suma_while ventana_20 = new Int_graf_suma_while();
        ventana_20.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sumas_con_while

    private void Sucesion_Fibonacci(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sucesion_Fibonacci
        int_graf_fibonacci ventana_21 = new int_graf_fibonacci();
        ventana_21.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Sucesion_Fibonacci

    private void B_salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_salir
        dispose();
    }//GEN-LAST:event_B_salir

    private void B_limpiar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_limpiar
        Input_num_1.setText("");
        Input_num_2.setText("");
        Input_resultado.setText("");
    }//GEN-LAST:event_B_limpiar

    private void Lista_operaciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_operaciones
        String seleccion = (String) Lista_operaciones.getSelectedItem();
        double numero_1 = Double.parseDouble(Input_num_1.getText());
        double numero_2 = Double.parseDouble(Input_num_2.getText());
        double resultado = 0;

        switch (seleccion) {
            case "resta" ->
            resultado = numero_1 - numero_2;
            case "suma" ->
            resultado = numero_1 + numero_2;
            case "multiplicación" ->
            resultado = numero_1 * numero_2;
            case "división" -> {
                if (numero_2 != 0) {
                    resultado = numero_1 / numero_2;
                } else {
                    JOptionPane.showMessageDialog(null, "No se puede dividir entre 0");
                    resultado = 0;
                }
            }
            default ->
            JOptionPane.showMessageDialog(null, "Operación no válida");
        }

        Input_resultado.setText(String.format("%.2f", resultado));
    }//GEN-LAST:event_Lista_operaciones

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Int_graf_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Int_graf_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Int_graf_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Int_graf_calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Int_graf_calculadora().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton B_limpiar;
    private javax.swing.JTextField Input_num_1;
    private javax.swing.JTextField Input_num_2;
    private javax.swing.JTextField Input_resultado;
    private javax.swing.JPanel Jpanel;
    private javax.swing.JComboBox<String> Lista_operaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
