/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gerardo_martinez.mavenproject1;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author Gerry-Mel
 */
public class mini_menu_areas extends javax.swing.JFrame {

    /**
     * Creates new form mini_menu_areas
     */
    public mini_menu_areas() {
        initComponents();
    }

    public class PanelDegradado extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g;

            GradientPaint gp = new GradientPaint(
                    0, 0, new Color(9, 13, 36),
                    0, getHeight(), new Color(20, 28, 74)
            );

            g2.setPaint(gp);
            g2.fillRect(0, 0, getWidth(), getHeight());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new PanelDegradado();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menu_areas = new javax.swing.JComboBox<>();
        B_salir = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Menú Áreas");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Selecciona una figura para calcular su área.");

        menu_areas.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        menu_areas.setForeground(new java.awt.Color(51, 153, 255));
        menu_areas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menú de áreas", "Área del circulo", "Área del rectángulo", "Área del trapecio", "Área del tríangulo" }));
        menu_areas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_areas(evt);
            }
        });

        B_salir.setBackground(new java.awt.Color(0, 51, 102));
        B_salir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        B_salir.setForeground(new java.awt.Color(102, 153, 255));
        B_salir.setText("Salir");
        B_salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_salir(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2)))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(menu_areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(B_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(menu_areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(B_salir)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jMenu1.setText("Primer parcial");
        jMenu1.setToolTipText("Ejercicios de áreas, magnitudes, otros.");

        jMenu3.setText("Calcular áreas");

        jMenuItem2.setText("Área del circulo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciruculo(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem5.setText("Área del rectángulo");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rectangulo(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem1.setText("Área del trapecio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trapecio(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuItem4.setText("Área del tríangulo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                triangulo(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        jMenu5.setText("Magnitides Físicas");

        jMenuItem3.setText("Densidad");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Densidad(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem7.setText("Masa");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Masa(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem6.setText("Volumen");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Volumen(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenu1.add(jMenu5);

        jMenu4.setText("Otros ejercicios");

        jMenuItem8.setText("Fórmula cuadrática");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_cua(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Segundo parcial");
        jMenu2.setToolTipText("Ejercicios condisonales: if, switch, repetitivas.");

        jMenu6.setText("Condisional if");

        jMenuItem9.setText("Calcular edad");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc_edad(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem11.setText("Producto");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Productos(evt);
            }
        });
        jMenu6.add(jMenuItem11);

        jMenuItem12.setText("Promedio");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Promedios(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuItem13.setText("Verificar números pares");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num_par(evt);
            }
        });
        jMenu6.add(jMenuItem13);

        jMenuItem14.setText("viajes");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Viajes(evt);
            }
        });
        jMenu6.add(jMenuItem14);

        jMenu2.add(jMenu6);

        jMenu7.setText("Estructura / switch");

        jMenuItem10.setText("Calculadora");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculadora(evt);
            }
        });
        jMenu7.add(jMenuItem10);

        jMenu2.add(jMenu7);

        jMenu9.setText("Estructuras de control iterativas");

        jMenu10.setText("Bucle for ");

        jMenuItem16.setText("Lista de Números");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list_num(evt);
            }
        });
        jMenu10.add(jMenuItem16);

        jMenuItem19.setText("Numeración");
        jMenu10.add(jMenuItem19);

        jMenuItem18.setText("Tabla del siete");
        jMenu10.add(jMenuItem18);

        jMenuItem17.setText("Tablas de multiplicar");
        jMenu10.add(jMenuItem17);

        jMenu9.add(jMenu10);

        jMenu11.setText("Bucle while ");

        jMenuItem22.setText("Contar hasta N / Mostrar texto");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contar_mostrar_texto(evt);
            }
        });
        jMenu11.add(jMenuItem22);

        jMenuItem21.setText("Suma de números");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suma_while(evt);
            }
        });
        jMenu11.add(jMenuItem21);

        jMenuItem20.setText("Sucesión Fibonacci");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sucession_fibonacci(evt);
            }
        });
        jMenu11.add(jMenuItem20);

        jMenu9.add(jMenu11);

        jMenu12.setText("Bucle do while ");
        jMenu9.add(jMenu12);

        jMenu2.add(jMenu9);

        jMenuBar1.add(jMenu2);

        jMenu8.setText("Menú inicio");
        jMenu8.setToolTipText("Regresar al menú principal.");

        jMenuItem15.setText("Menú inicio");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_inicio(evt);
            }
        });
        jMenu8.add(jMenuItem15);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menu_areas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_areas
        String seleccion = (String) menu_areas.getSelectedItem();
        switch (seleccion) {
            case "Área del circulo":
                int_graf_circ ventana_1 = new int_graf_circ();
                ventana_1.setVisible(true);
                break;
            case "Área del rectángulo":
                Interfaz_grafica_Rec ventana_2 = new Interfaz_grafica_Rec();
                ventana_2.setVisible(true);
                break;
            case "Área del trapecio":
                Int_graf_trap ventana_3 = new Int_graf_trap();
                ventana_3.setVisible(true);
                break;
            case "Área del tríangulo":
                Interfaz_grafica_Tri ventana_4 = new Interfaz_grafica_Tri();
                ventana_4.setVisible(true);
                break;

        }

    }//GEN-LAST:event_menu_areas

    private void ciruculo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciruculo
        int_graf_circ ventana_1 = new int_graf_circ();
        ventana_1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ciruculo

    private void rectangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rectangulo
        Interfaz_grafica_Rec ventana_2 = new Interfaz_grafica_Rec();
        ventana_2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rectangulo

    private void trapecio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trapecio
        Int_graf_trap ventana_3 = new Int_graf_trap();
        ventana_3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_trapecio

    private void triangulo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_triangulo
        Interfaz_grafica_Tri ventana_4 = new Interfaz_grafica_Tri();
        ventana_4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_triangulo

    private void Densidad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Densidad
        Int_graf_densidad ventana_5 = new Int_graf_densidad();
        ventana_5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Densidad

    private void Masa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Masa
        Int_graf_Masa ventana_6 = new Int_graf_Masa();
        ventana_6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Masa

    private void Volumen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Volumen
        int_graf_volumen ventana_7 = new int_graf_volumen();
        ventana_7.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Volumen

    private void Form_cua(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_cua
        int_graf_formula_cu ventana_8 = new int_graf_formula_cu();
        ventana_8.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Form_cua

    private void calc_edad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc_edad
        Int_graf_calc_edad ventana_9 = new Int_graf_calc_edad();
        ventana_9.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calc_edad

    private void Productos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Productos
        int_graf_produc ventana_10 = new int_graf_produc();
        ventana_10.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Productos

    private void Promedios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Promedios
        calc_calif ventana_11 = new calc_calif();
        ventana_11.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Promedios

    private void num_par(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num_par
        Int_graf_numero_par ventana_12 = new Int_graf_numero_par();
        ventana_12.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_num_par

    private void Viajes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Viajes
        Int_graf_viajes ventana_13 = new Int_graf_viajes();
        ventana_13.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Viajes

    private void Calculadora(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculadora
        Int_graf_calculadora ventana_14 = new Int_graf_calculadora();
        ventana_14.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Calculadora

    private void menu_inicio(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_inicio
        Menu_gui ventana_15 = new Menu_gui();
        ventana_15.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_inicio

    private void B_salir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_salir
        dispose();
    }//GEN-LAST:event_B_salir

    private void list_num(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list_num
        int_graf_lista_num ventana_16 = new int_graf_lista_num();
        ventana_16.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_list_num

    private void contar_mostrar_texto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contar_mostrar_texto
        int_grafi_while ventana_20 = new int_grafi_while();
        ventana_20.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_contar_mostrar_texto

    private void suma_while(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suma_while
        Int_graf_suma_while ventana_21 = new Int_graf_suma_while();
        ventana_21.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_suma_while

    private void sucession_fibonacci(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucession_fibonacci
        int_graf_fibonacci ventana_22 = new int_graf_fibonacci();
        ventana_22.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sucession_fibonacci

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mini_menu_areas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mini_menu_areas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mini_menu_areas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mini_menu_areas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mini_menu_areas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton B_salir;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> menu_areas;
    // End of variables declaration//GEN-END:variables
}
